name: Publish Package to GitHub NPM Registry

on: 
  release: 
    types: published 

    
jobs:
    npm-package:
      permissions:                     #added
        packages: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Setup NodeJS Version - 20.x
          uses: actions/setup-node@v4
          with:
              node-version: '20.x'
              registry-url: 'https://npm.pkg.github.com/'
        
        - name: Install NPM Dependencies
          run: npm install
        
        - name: NPM Publish
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}